frr defaults traditional
hostname isp1
log syslog informational
service integrated-vtysh-config
!
! ISP1 - AS 65101. Customer: AS 65000 (192.0.2.0/24 and more-specifics up to /25)
ip prefix-list CUST-AS65000 seq 5 permit 192.0.2.0/24 le 25
ip prefix-list DEFAULT seq 5 permit 0.0.0.0/0
!
bgp community-list standard CUST-BACKUP seq 5 permit 65101:80
!
route-map CUSTOMER-IN permit 10
 match ip address prefix-list CUST-AS65000
 match community CUST-BACKUP
 set local-preference 80
exit
route-map CUSTOMER-IN permit 20
 match ip address prefix-list CUST-AS65000
 set local-preference 200
exit
!
route-map ALL permit 10
exit
!
router bgp 65101
 bgp router-id 10.255.101.1
 neighbor 198.51.100.2 remote-as 65000
 neighbor 198.51.100.2 description customer-e1
 neighbor 198.51.100.10 remote-as 65102
 neighbor 198.51.100.10 description peer-isp2
 !
 address-family ipv4 unicast
  network 198.18.1.0/24
  neighbor 198.51.100.2 default-originate
  neighbor 198.51.100.2 route-map CUSTOMER-IN in
  neighbor 198.51.100.2 route-map ALL out
  neighbor 198.51.100.10 route-map ALL in
  neighbor 198.51.100.10 route-map ALL out
 exit-address-family
exit
!
end
